version: "3.9"

services:
  tgmessagecopy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tgmessagecopy
    restart: unless-stopped
    volumes:
      - ./data:/app/data

